### ISSUE TITLE
Iteration 2 checklist

### ISSUE THREAD

**Issue by ChantalForget** [sstone93/MAGIC#69]
- [x] Ghosts
- [ ] Cheat mode
  -         Select sound and warning chits of an empty tile
  -         Choose die roll
- [x] Start characters at different dwellings
- [x] Do special abilities of characters
- [x] Show treasures in hover over
- [x] Support fatigue
- [x] Change treasures to gold with notoriety and fame
  -         Must support certain specific treasures!
- [x] Treasures appear on map
- [x] Secret passages and tunnels
- [x] Picking up treasures when searching **not tested**
- [x] Multi-round combat between characters
- [x] Lost Castle and Lost City
- [x] Implement list of real treasures to appear
- [x] Random placement of chits
- [x] Support move restrictions like caves and mountains
- [x] Support selling and ~~blocking~~ with natives at the dwellings
- [x] Support monsters appearing and blocking (only need 1 monster type)
- [x] Support character to monster combat, with up to 6 monsters
- [x] End of game triggers proper networking shutdown

Above and beyond!
- [ ] Support alternative boards
- [x] Support carrying capacity
- [x] Support more treasures and monsters
- [x] Improve GUI to zoom or other fancy things
- [ ] Support horses
- [ ] Support multiple characters vs monsters combat
- [ ] Support magic
- [ ] Support hiring and use of natives

**Comment by SunsetBlade** [comment]
I spoke to him about board building (he said he was going to clarify in class today anyways) but what he will be wanting as a possible "extra" feature is proper board creation.

What he seems to mean by this is that you can specify how the tiles fit together (like we already do), but what we cannot do, is hard-code the co-ordinates of each tile (like we currently do). Furthermore is the implication that we would need a unique hover-over for each clearing on the tile, and those could not be hard-coded either (though coding offsets is most likely fine).

This is likely something to do later (if at all) since it will be fairly complex, unless you feel super motivated (@sstone93).

**Comment by sstone93** [comment]
@SunsetBlade OMG I hate this freaking board!!!

**Comment by SunsetBlade** [comment]
I think our focus for tomorrow should be finalizing our GUI design so we
don't create more work where we don't need to ><.

On Thu, Mar 5, 2015 at 12:21 PM, sstone93 notifications@github.com wrote:

> @SunsetBlade https://github.com/SunsetBlade OMG I hate this freaking
> board!!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sstone93/MAGIC/issues/69#issuecomment-77407436.

## 

Nicholas Laws

**Comment by sstone93** [comment]
Yes, @ChantalForget , @SunsetBlade , @michaelcatt if possible I would like to nail down what we need to be able to show, and get from the GUI at the different points during the gameplay. This of course can (and probably will) change, but if I have a good idea of what is needed I can start chipping away at it and hopefully we won't have as many issues trying to glue things together this time.

**Comment by ChantalForget** [comment]
cool cool :+1:
